
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '4C718A57C1EF98EA2BED19C1948871DE'
    
_lr_action_items = {'TEAM':([0,1,2,3,4,5,6,7,8,16,18,20,27,28,30,31,],[10,10,-2,-3,-4,-5,-6,-7,-8,-1,-12,-13,-14,-10,-9,-11,]),'WEAK_TWO':([0,1,2,3,4,5,6,7,8,16,18,20,27,28,30,31,],[11,11,-2,-3,-4,-5,-6,-7,-8,-1,-12,-13,-14,-10,-9,-11,]),'N':([0,1,2,3,4,5,6,7,8,16,18,20,21,27,28,30,31,],[12,12,-2,-3,-4,-5,-6,-7,-8,-1,-12,-13,12,-14,-10,-9,-11,]),'E':([0,1,2,3,4,5,6,7,8,16,18,20,21,27,28,30,31,],[13,13,-2,-3,-4,-5,-6,-7,-8,-1,-12,-13,13,-14,-10,-9,-11,]),'S':([0,1,2,3,4,5,6,7,8,16,18,20,21,27,28,30,31,],[14,14,-2,-3,-4,-5,-6,-7,-8,-1,-12,-13,14,-14,-10,-9,-11,]),'W':([0,1,2,3,4,5,6,7,8,16,18,20,21,27,28,30,31,],[15,15,-2,-3,-4,-5,-6,-7,-8,-1,-12,-13,15,-14,-10,-9,-11,]),'$end':([1,2,3,4,5,6,7,8,16,18,20,27,28,30,31,],[0,-2,-3,-4,-5,-6,-7,-8,-1,-12,-13,-14,-10,-9,-11,]),'EQUAL':([9,12,13,14,15,],[17,-16,-17,-18,-19,]),'TILDE':([9,12,13,14,15,],[19,-16,-17,-18,-19,]),';':([9,10,12,13,14,15,22,23,25,26,32,],[18,20,-16,-17,-18,-19,27,28,30,31,-15,]),'BY':([11,],[21,]),'DISTRIBUTION':([17,19,],[23,25,]),'NUMBER':([17,29,],[24,32,]),'MINUS':([24,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'queries':([0,],[1,]),'query':([0,1,],[2,16,]),'point_range':([0,1,],[3,3,]),'exact_distribution':([0,1,],[4,4,]),'unordered_distribution':([0,1,],[5,5,]),'dealer':([0,1,],[6,6,]),'vulnerable':([0,1,],[7,7,]),'weak_two':([0,1,],[8,8,]),'player':([0,1,21,],[9,9,26,]),'range':([17,],[22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> queries","S'",1,None,None,None),
  ('queries -> queries query','queries',2,'p_queries','biddingParser.py',16),
  ('queries -> query','queries',1,'p_queries','biddingParser.py',17),
  ('query -> point_range','query',1,'p_query','biddingParser.py',25),
  ('query -> exact_distribution','query',1,'p_query','biddingParser.py',26),
  ('query -> unordered_distribution','query',1,'p_query','biddingParser.py',27),
  ('query -> dealer','query',1,'p_query','biddingParser.py',28),
  ('query -> vulnerable','query',1,'p_query','biddingParser.py',29),
  ('query -> weak_two','query',1,'p_query','biddingParser.py',30),
  ('unordered_distribution -> player TILDE DISTRIBUTION ;','unordered_distribution',4,'p_unordered_distribution','biddingParser.py',35),
  ('exact_distribution -> player EQUAL DISTRIBUTION ;','exact_distribution',4,'p_exact_distribution','biddingParser.py',39),
  ('weak_two -> WEAK_TWO BY player ;','weak_two',4,'p_weak_two','biddingParser.py',43),
  ('dealer -> player ;','dealer',2,'p_dealer','biddingParser.py',47),
  ('vulnerable -> TEAM ;','vulnerable',2,'p_vulnerable','biddingParser.py',51),
  ('point_range -> player EQUAL range ;','point_range',4,'p_point_range','biddingParser.py',55),
  ('range -> NUMBER MINUS NUMBER','range',3,'p_range','biddingParser.py',61),
  ('player -> N','player',1,'p_player','biddingParser.py',65),
  ('player -> E','player',1,'p_player','biddingParser.py',66),
  ('player -> S','player',1,'p_player','biddingParser.py',67),
  ('player -> W','player',1,'p_player','biddingParser.py',68),
]
