
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'DF2140055E96D790272D68F8707E2295'
    
_lr_action_items = {'TEAM':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,35,36,38,39,40,41,],[12,12,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,-18,-12,-11,-15,-13,-14,]),'WEAK_TWO':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,35,36,38,39,40,41,],[13,13,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,-18,-12,-11,-15,-13,-14,]),'ONE_NO_TRUMP':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,35,36,38,39,40,41,],[14,14,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,-18,-12,-11,-15,-13,-14,]),'ONE_CLUB':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,35,36,38,39,40,41,],[15,15,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,-18,-12,-11,-15,-13,-14,]),'N':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,25,26,27,35,36,38,39,40,41,],[16,16,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,16,16,16,-18,-12,-11,-15,-13,-14,]),'E':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,25,26,27,35,36,38,39,40,41,],[17,17,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,17,17,17,-18,-12,-11,-15,-13,-14,]),'S':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,25,26,27,35,36,38,39,40,41,],[18,18,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,18,18,18,-18,-12,-11,-15,-13,-14,]),'W':([0,1,2,3,4,5,6,7,8,9,10,20,22,24,25,26,27,35,36,38,39,40,41,],[19,19,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,19,19,19,-18,-12,-11,-15,-13,-14,]),'$end':([1,2,3,4,5,6,7,8,9,10,20,22,24,35,36,38,39,40,41,],[0,-2,-3,-4,-5,-6,-7,-8,-9,-10,-1,-16,-17,-18,-12,-11,-15,-13,-14,]),'EQUAL':([11,16,17,18,19,],[21,-20,-21,-22,-23,]),'TILDE':([11,16,17,18,19,],[23,-20,-21,-22,-23,]),';':([11,12,16,17,18,19,28,29,31,32,33,34,42,],[22,24,-20,-21,-22,-23,35,36,38,39,40,41,-19,]),'BY':([13,14,15,],[25,26,27,]),'DISTRIBUTION':([21,23,],[29,31,]),'NUMBER':([21,37,],[30,42,]),'MINUS':([30,],[37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'queries':([0,],[1,]),'query':([0,1,],[2,20,]),'point_range':([0,1,],[3,3,]),'exact_distribution':([0,1,],[4,4,]),'unordered_distribution':([0,1,],[5,5,]),'dealer':([0,1,],[6,6,]),'vulnerable':([0,1,],[7,7,]),'weak_two':([0,1,],[8,8,]),'one_no_trump':([0,1,],[9,9,]),'one_club':([0,1,],[10,10,]),'player':([0,1,25,26,27,],[11,11,32,33,34,]),'range':([21,],[28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> queries","S'",1,None,None,None),
  ('queries -> queries query','queries',2,'p_queries','biddingParser.py',16),
  ('queries -> query','queries',1,'p_queries','biddingParser.py',17),
  ('query -> point_range','query',1,'p_query','biddingParser.py',25),
  ('query -> exact_distribution','query',1,'p_query','biddingParser.py',26),
  ('query -> unordered_distribution','query',1,'p_query','biddingParser.py',27),
  ('query -> dealer','query',1,'p_query','biddingParser.py',28),
  ('query -> vulnerable','query',1,'p_query','biddingParser.py',29),
  ('query -> weak_two','query',1,'p_query','biddingParser.py',30),
  ('query -> one_no_trump','query',1,'p_query','biddingParser.py',31),
  ('query -> one_club','query',1,'p_query','biddingParser.py',32),
  ('unordered_distribution -> player TILDE DISTRIBUTION ;','unordered_distribution',4,'p_unordered_distribution','biddingParser.py',37),
  ('exact_distribution -> player EQUAL DISTRIBUTION ;','exact_distribution',4,'p_exact_distribution','biddingParser.py',41),
  ('one_no_trump -> ONE_NO_TRUMP BY player ;','one_no_trump',4,'p_one_no_trump','biddingParser.py',45),
  ('one_club -> ONE_CLUB BY player ;','one_club',4,'p_one_club','biddingParser.py',49),
  ('weak_two -> WEAK_TWO BY player ;','weak_two',4,'p_weak_two','biddingParser.py',53),
  ('dealer -> player ;','dealer',2,'p_dealer','biddingParser.py',57),
  ('vulnerable -> TEAM ;','vulnerable',2,'p_vulnerable','biddingParser.py',61),
  ('point_range -> player EQUAL range ;','point_range',4,'p_point_range','biddingParser.py',65),
  ('range -> NUMBER MINUS NUMBER','range',3,'p_range','biddingParser.py',71),
  ('player -> N','player',1,'p_player','biddingParser.py',75),
  ('player -> E','player',1,'p_player','biddingParser.py',76),
  ('player -> S','player',1,'p_player','biddingParser.py',77),
  ('player -> W','player',1,'p_player','biddingParser.py',78),
]
